### ISSUE TITLE
Implement `Gridspec`

### ISSUE THREAD

**Issue by geetmankar** [cpmech/plotpy#31]
I'd like to know if `plt.Gridspec` can be implemented so that the following:

```python3
fig = plt.figure(figsize=(4, 6), dpi=100)
grid = plt.GridSpec(3, 1, wspace=0, hspace=0.7)
ax1 = plt.subplot(grid[0:2, 0])
ax2 = plt.subplot(grid[2, 0])

ax1.plot(...)
ax2.plot(...)
```

can be used to scale the ratios of subplots

**Comment by cpmech** [comment]
Hi,

Thanks again.

I have implemented this feature using the methods `set_gridspec(...)` and `set_subplot_grid(...)` of `Plot`.

For example, your code would be something like this:

```rust
let mut plot = Plot::new();
plot.set_gridspec("g", 3, 1, "wspace=0, hspace=0.7")
    .set_subplot_grid("g", "0:2", "0")
    .add(&curve1)
    .set_subplot_grid("g", "2", "0")
    .add(&curve2);
```

Note that we must use a handle such as `"g"` (this is one way to pass an internal python variable from a rust function to another), and the range parameters must be a string.

The figure below is the result of the code above.

![figures/integ_gridspec_1.svg
](https://raw.githubusercontent.com/cpmech/plotpy/main/figures/integ_gridspec_1.svg)

See more examples here:
https://github.com/cpmech/plotpy/blob/c7febcb49f62772416725d8879fda7de2ad50438/tests/test_subplot.rs#L54

See also another example here:
https://github.com/cpmech/plotpy/blob/c7febcb49f62772416725d8879fda7de2ad50438/tests/test_subplot.rs#L87

With the following output.
![figures/integ_gridspec_2.svg](https://raw.githubusercontent.com/cpmech/plotpy/main/figures/integ_gridspec_2.svg)

Cheers.

**Comment by geetmankar** [comment]
Thanks! And also thanks for making this frontend for python, others like `plotters` (no anti-aliasing) and `rustplotlib` (Good but abandoned and doesn't have as many features) are a little lacking in features.
