### ISSUE TITLE
Windows Error: "python3 failed; please see the log file"

### ISSUE THREAD

**Issue by supernova4869** [cpmech/plotpy#49]
I met an error about python3 in windows system. I know that on linux system, the `python3` command is executable, but on windows we use `python` insteadof `python3`. Is their any way to avoid this error? Should I set an alias of python as python3?
Meanwhile, I have tyied to add this line before `Plot::new()`, but it did not work.
```
Command::new("cmd")
        .args(["/C", "doskey python3=python"])
        .output()
        .expect("failed to execute process");
```

**Comment by cpmech** [comment]
Hi, I've added a function to set python3 executable; for example:

```rust
let mut plot = Plot::new();
plot.set_python_exe("python")
    .add(...)
    .save(...)?;
```

Can you please try it? (it's on version 1.1.1)

**Comment by supernova4869** [comment]
Thanks a lot. It works very well.  ;-D
