### ISSUE TITLE
Python3 Failed. please see the log file

### ISSUE THREAD

**Issue by Shrav108** [cpmech/plotpy#52]
I am trying to plot some graph and want to include in egui interface. When I create a graph and try to save, I get this error

Error : _python3 failed; please see the log file_

What is the solution ?

Also, How to plot 2 curves/lines with the same x axis like given below ?

![image](https://github.com/user-attachments/assets/9a1ea977-f996-4279-8782-9b58fa1f633e)

**Comment by cpmech** [comment]
Hi,

Can you please show your Rust code and the python log file?

I've implemented the feature for the plot with dual Y and a single X (known as twin-x).

Basically, we can call the `draw_with_twinx` function **after** calling the `draw` function.

 For example, see the code below (and the figure).

```rust
use plotpy::{Curve, Plot, StrError};
use std::f64::consts::PI;

fn main() -> Result<(), StrError> {
    // data
    let np = 201;
    let mut x = vec![0.0; np];
    let mut y1 = vec![0.0; np];
    let mut y2 = vec![0.0; np];
    let dx = 4.0 / (np as f64);
    for i in 0..np {
        x[i] = (i as f64) * dx;
        y1[i] = f64::exp(x[i]);
        y2[i] = f64::sin(2.0 * PI * x[i]);
    }

    // curve
    let mut curve = Curve::new();
    curve.set_line_color("red").draw(&x, &y1);
    curve.set_line_color("blue").draw_with_twin_x(&y2);

    // add curve to plot
    let mut plot = Plot::new();
    plot.add(&curve) // must occur before set twinx options
        .grid_and_labels("time (s)", "exp function")
        .set_label_x_color("green")
        .set_label_y_color("red")
        .set_label_y_twinx("sin function")
        .set_label_y_twinx_color("blue");

    // save figure
    plot.save("/tmp/plotpy/doc_tests/doc_curve_twinx.svg")?;
    Ok(())
}
```

![doc_curve_twinx](https://github.com/user-attachments/assets/cc01e63b-17d5-489b-af80-165eba8e08c8)

**Comment by Shrav108** [comment]
Thank you for showing how it is done.  I ran your code on windows. here is the log file results

Error:
> Error: "python3 failed; please see the log file"

Log File :

> Traceback (most recent call last):
>   File "D:\Hydrostatic\hydrostatic\doc_curve_twinx.py", line 3, in <module>
>     import numpy as np
> ModuleNotFoundError: No module named 'numpy'

**Comment by Shrav108** [comment]
Does this library work on windows ?

**Comment by cpmech** [comment]
Hi,

I haven't tested it on Windows. But it seems that others have successfully (see this: https://github.com/cpmech/plotpy/issues/49).  

I suppose that if you have python3 + numpy + scipy + matplotlib installed, everything should work.

Cheers
