### ISSUE TITLE
Print strings for tick labels

### ISSUE THREAD

**Issue by lobneroO** [cpmech/plotpy#56]
Maybe I missed it somewhere, but the examples certainly don't have it.
In the original matplotlib you can use custom strings as tick labels on the axes, such as this x axis:

![image](https://user-images.githubusercontent.com/17877050/182021209-8dd4ed3d-d114-409d-8f4d-f76aad437d36.png)

In matplotlib there is a `set_xticklables` for this but in the plotpy I cannot find anything along these lines.

**Comment by cpmech** [comment]
Hi,

I've implemented this feature.

See the second example from here: https://docs.rs/plotpy/latest/plotpy/struct.Plot.html

For instance, the following snippet changes the tick labels:

```rust
// set tick labels
let mut plot = Plot::new();
let ticks: Vec<_> = (0..vegetables.len()).into_iter().collect();
plot.add(&img)
    .set_rotation_ticks_x(45.0)
    .set_ticks_x_labels(&ticks, &farmers)
    .set_ticks_y_labels(&ticks, &vegetables);
```

![doc_plot_2](https://github.com/user-attachments/assets/10de0371-889f-47e0-8efe-c19b7e67a10c)

Cheers
