### ISSUE TITLE
legend configuration

### ISSUE THREAD

**Issue by wangjiawen2013** [cpmech/plotpy#76]
Hi,
Here is a chunk of code adopted from plot.rs.  `.legend()` is a method of `plot` and has only one parameter `&mut self`, `Legend::new()` can construct a default legend, but how to pass a legend with customized options to `plot` ? 
![image](https://github.com/user-attachments/assets/860825bf-d73a-46a7-aed3-21aa6e96d7fd)

**Comment by cpmech** [comment]
The `legend()` function in `Plot` can only add a legend with default values.

For a more customized version, we need to use the `Legend` struct directly. See https://docs.rs/plotpy/latest/plotpy/struct.Legend.html
