### ISSUE TITLE
number trait

### ISSUE THREAD

**Issue by wangjiawen2013** [cpmech/plotpy#85]
Hi,
Now we must check the type `U` to make sure it is a number, is it better to define a number trait to make full use of rust's type system and the type checking ?
![image](https://github.com/user-attachments/assets/902dcfe6-d3b3-4aac-8669-ef43c8ea98fb)

**Comment by cpmech** [comment]
It is a good idea to auto check for number types.  We could use `num-traits` as I did in https://github.com/cpmech/russell

When I started `plotpy`, I didn't know about `num-traits`... I think this would require some effort to implement now.

**Comment by cpmech** [comment]
This has been improved with `num-traits`. See #94
