### ISSUE TITLE
with and without crate

### ISSUE THREAD

**Issue by wangjiawen2013** [cpmech/plotpy#91]
Hi,
This is a snippet of code adopted from `lib.rs`:
```rust
mod plot;
mod slope_icon;
mod super_title_params;
mod surface;
mod surface_geometry;
mod text;
pub use crate::as_matrix::*;
pub use crate::as_vector::*;
pub use crate::auxiliary::*;
pub use crate::barplot::*;
pub use crate::boxplot::*;
pub use crate::canvas::*;
```
what's the difference between `pub use crate::as_matrix::*;` and `pub use as_matrix::*;` here ?  Can the `crate` be omitted ?

**Comment by cpmech** [comment]
You're right; we don't need the word `crate` here. I guess I left the word `crate` when I was learning Rust. I've simplified these statements in #92
